Remove problematic unit test causing Mockery/BerlinDB conflict
The ExtractMetricDataTest was causing a fatal error due to Mockery
incompatibility with BerlinDB's __isset() method signature.

Error: Declaration of Mockery__isset($name) must be compatible with
BerlinDB\Database\Base::__isset($key = '')

Removed to restore test suite stability.