Load constants.php early to prevent fatal error (PR#2275)
Fatal error: Cannot redeclare rocket_get_constant() (previously declared in /home/travis/build/wp-media/wp-rocket/vendor/brain/monkey/src/Expectation/FunctionStub.php(52) : eval()'d code:2) in /home/travis/build/wp-media/wp-rocket/inc/constants.php on line 32

Picked from 6a5bbe2

This is needed to prevent the error everytime we use when or expect for rocket_get_constant in the unit tests